// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkvzjM_CzLsShb4WCNt6S1weV1vXjAItY',
    appId: '1:565864761647:web:acbee542951288be0ef9da',
    messagingSenderId: '565864761647',
    projectId: 'auctionax-f2e3d',
    authDomain: 'auctionax-f2e3d.firebaseapp.com',
    databaseURL: 'https://auctionax-f2e3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auctionax-f2e3d.appspot.com',
    measurementId: 'G-39DP3W4CS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ06SWHtDYdqVWb8umaknB78ehhwbbVgQ',
    appId: '1:565864761647:android:5ed78ab664ce6fc90ef9da',
    messagingSenderId: '565864761647',
    projectId: 'auctionax-f2e3d',
    databaseURL: 'https://auctionax-f2e3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auctionax-f2e3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGU5k1yiiY9OOa5bbXj0CofpwqbP9txc0',
    appId: '1:565864761647:ios:e82219801d7d54730ef9da',
    messagingSenderId: '565864761647',
    projectId: 'auctionax-f2e3d',
    databaseURL: 'https://auctionax-f2e3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auctionax-f2e3d.appspot.com',
    iosClientId: '565864761647-rg3oi7j2olupbo7jdadbgln1slktnp3b.apps.googleusercontent.com',
    iosBundleId: 'th.co.auctionexpress.mobile',
  );
}
